// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZbMUHtAI-u1EjGpfrbtWWxBRcsvk42Zs',
    appId: '1:226431785429:web:5fd2fa109f6917bcb6455c',
    messagingSenderId: '226431785429',
    projectId: 'lutter-authentication',
    authDomain: 'lutter-authentication.firebaseapp.com',
    storageBucket: 'lutter-authentication.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM5nM8IecpOXGvdAQSVlZ9mAtnN4Crsoo',
    appId: '1:226431785429:android:48764a9d0d72ee8eb6455c',
    messagingSenderId: '226431785429',
    projectId: 'lutter-authentication',
    storageBucket: 'lutter-authentication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALsac42--UQkiSpJ_qNWLFOTwmlqzRb_I',
    appId: '1:226431785429:ios:9d75cc1b9fc973d8b6455c',
    messagingSenderId: '226431785429',
    projectId: 'lutter-authentication',
    storageBucket: 'lutter-authentication.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALsac42--UQkiSpJ_qNWLFOTwmlqzRb_I',
    appId: '1:226431785429:ios:9d75cc1b9fc973d8b6455c',
    messagingSenderId: '226431785429',
    projectId: 'lutter-authentication',
    storageBucket: 'lutter-authentication.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZbMUHtAI-u1EjGpfrbtWWxBRcsvk42Zs',
    appId: '1:226431785429:web:b3b70eb41515129bb6455c',
    messagingSenderId: '226431785429',
    projectId: 'lutter-authentication',
    authDomain: 'lutter-authentication.firebaseapp.com',
    storageBucket: 'lutter-authentication.firebasestorage.app',
  );
}
