// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADMo3F1PY_bbEiyu5gvw-4DmWwiaRfmlo',
    appId: '1:87411107443:web:ed598ff8dfea8ee876ec06',
    messagingSenderId: '87411107443',
    projectId: 'fir-auth-demo-e8a01',
    authDomain: 'fir-auth-demo-e8a01.firebaseapp.com',
    storageBucket: 'fir-auth-demo-e8a01.firebasestorage.app',
    measurementId: 'G-C42KT69LQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ-a1P7Y7P1o9bxjGtD3Cnkpw7wnXwTX0',
    appId: '1:87411107443:android:469e592446e5955d76ec06',
    messagingSenderId: '87411107443',
    projectId: 'fir-auth-demo-e8a01',
    storageBucket: 'fir-auth-demo-e8a01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBu3KBs94JqujKXaCJh3R2lu-lkQ_6-aQ',
    appId: '1:87411107443:ios:684186e808b83f7b76ec06',
    messagingSenderId: '87411107443',
    projectId: 'fir-auth-demo-e8a01',
    storageBucket: 'fir-auth-demo-e8a01.firebasestorage.app',
    iosBundleId: 'com.example.demoweek3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBu3KBs94JqujKXaCJh3R2lu-lkQ_6-aQ',
    appId: '1:87411107443:ios:684186e808b83f7b76ec06',
    messagingSenderId: '87411107443',
    projectId: 'fir-auth-demo-e8a01',
    storageBucket: 'fir-auth-demo-e8a01.firebasestorage.app',
    iosBundleId: 'com.example.demoweek3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADMo3F1PY_bbEiyu5gvw-4DmWwiaRfmlo',
    appId: '1:87411107443:web:e4ce68bc59076d5776ec06',
    messagingSenderId: '87411107443',
    projectId: 'fir-auth-demo-e8a01',
    authDomain: 'fir-auth-demo-e8a01.firebaseapp.com',
    storageBucket: 'fir-auth-demo-e8a01.firebasestorage.app',
    measurementId: 'G-RV320FRHK5',
  );
}
